version: "3.8"

volumes:
  admin_web_node_modules:
  user_web_node_modules:
  user_app_node_modules: 
  admin_web_svelte:
  user_web_svelte:
  user_app_svelte:

services:
  mariadb-bikes:
    image: "mariadb:10.11.6"
    container_name: "mariadb-bikes"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - "./server/mariadb/csv/:/csv/"
      - "./server/mariadb/sql/:/sql/"
      - "./server/mariadb/setup-bikes.sql:/docker-entrypoint-initdb.d/setup-bikes.sql"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "always"

  mariadb-test:
    image: "mariadb:10.11.6"
    container_name: "mariadb-test"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: test
      MYSQLD_LOCAL_INFILE: "1"
    volumes:
      - "./server/mariadb/csv/:/csv/"
      - "./server/mariadb/sql/:/sql/"
      - "./server/mariadb/setup-test.sql:/docker-entrypoint-initdb.d/setup-test.sql"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "always"

  server:
    build:
      context: "./server/"
      dockerfile: "./server/Dockerfile"
    container_name: "server"
    environment:
      DB_HOST: ${DB_SERVICE_NAME}
      DB_TEST_HOST: ${TEST_SERVICE_NAME}
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_NAME}
      TEST_DATABASE: ${TEST_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./server/server/coverage:/server/coverage
      - ./server/server/package.json:/server/package.json
      - ./server/server/package-lock.json:/server/package-lock.json
      - ./server/server/mocha.json:/server/mocha.json
      - ./server/server/app.js:/server/app.js
      - ./server/server/server.js:/server/server.js
      - ./server/server/routes/:/server/routes/
      - ./server/server/test/:/server/test/
      - ./server/server/src/:/server/src/
      - ./server/server/views/:/server/views/
      - ./server/server/public/:/server/public/
      - ./server/server/.eslintignore:/server/.eslintignore
      - ./server/server/.eslintrc.json:/server/.eslintrc.json
      - ./server/server/.prettierignore:/server/.prettierignore
    ports:
      - "1337:1337"
    depends_on:
      mariadb-bikes:
        condition: service_healthy
      mariadb-test:
        condition: service_healthy
    restart: "always"

  python:
    container_name: "bike-python"
    build:
      context: "./bike-brain/"
      dockerfile: "./Dockerfile"
    working_dir: "/bike/app"
    volumes:
      - "./bike-brain/app/:/bike/app"
    links:
      - "server:express-server"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTEST_ADDOPTS=-p no:cacheprovider
      - API_URL=${PYTHON_API_URL}
      - API_KEY=${PYTHON_API_KEY}
    depends_on:
      - server
    command: "python app.py"
    restart: "on-failure"

  admin-web-service:
    container_name: "admin-web-container"
    build:
      context: "./admin-web-client/"
      dockerfile: "./Dockerfile-dev"
    environment:
      # Explicitly tell SvelteKit where the app is being served
      # to avoid the "Cross-site POST form submissions are forbidden" error
      # when using form actions with the node adapter
      - ORIGIN=http://localhost:5173
      - PUBLIC_MAPTILER_API_KEY=${PUBLIC_MAPTILER_API_KEY}
      - PUBLIC_REST_API_URL=${PUBLIC_REST_API_URL}
      - PRIVATE_REST_API_KEY=${AW_PRIVATE_REST_API_KEY}
    volumes:
      - "./admin-web-client/:/app"
      - "admin_web_node_modules:/app/node_modules"
      - "admin_web_svelte:/app/.svelte-kit"
    depends_on:
      - server
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        npm run prep-docker
        npm run dev -- --host
    links:
      - "server:express-server"
    ports:
      - 3000:5173

  user-web-service:
    container_name: user-web-container
    build:
      context: "./user-web-client/"
      dockerfile: "./Dockerfile-dev"
    environment:
      # Explicitly tell SvelteKit where the app is being served
      # to avoid the "Cross-site POST form submissions are forbidden" error
      # when using form actions with the node adapter
      - ORIGIN=http://localhost:5173
      - PUBLIC_MAPTILER_API_KEY=${PUBLIC_MAPTILER_API_KEY}
      - PUBLIC_REST_API_URL=${PUBLIC_REST_API_URL}
      - PRIVATE_REST_API_KEY=${UW_PRIVATE_REST_API_KEY}
      - PUBLIC_GITHUB_ID=${UW_PUBLIC_GITHUB_ID}
      - GITHUB_SECRET=${UW_GITHUB_SECRET}
    volumes:
      - "./user-web-client/:/app"
      - "user_web_node_modules:/app/node_modules"
      - "user_web_svelte:/app/.svelte-kit"
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        npm run prep-docker
        npm run dev -- --host
    links:
      - "server:express-server"
    ports:
      - 5173:5173

  user-app-service:
    container_name: user-app-container
    build:
      context: "./user-app-client/"
      dockerfile: "./Dockerfile-dev"
    environment:
      # Explicitly tell SvelteKit where the app is being served
      # to avoid the "Cross-site POST form submissions are forbidden" error
      # when using form actions with the node adapter
      - ORIGIN=http://localhost:5174
      - PUBLIC_MAPTILER_API_KEY=${PUBLIC_MAPTILER_API_KEY}
      - PUBLIC_REST_API_URL=${PUBLIC_REST_API_URL}
      - PRIVATE_REST_API_KEY=${UA_PRIVATE_REST_API_KEY}
      - PUBLIC_GITHUB_ID=${UA_PUBLIC_GITHUB_ID}
      - GITHUB_SECRET=${UA_GITHUB_SECRET}
    volumes:
      - "./user-app-client/:/app"
      - "user_app_node_modules:/app/node_modules"
      - "user_app_svelte:/app/.svelte-kit"
    restart: always  
    command:
      - /bin/sh
      - -c
      - |
        npm run prep-docker
        npm run dev -- --host
    links:
      - "server:express-server"
    ports:
      - 5174:5174
